# Generated by Django 5.2.1 on 2025-05-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cc_1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cc_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
